### ISSUE TITLE
빱빱이 살리기 청원

### ISSUE THREAD

**Issue by luke2327** [artvelop/poppopmim#4]
### 빱빱이 살리기

우리는 빱빱이를 살리기 위해 모였습니다.

저 간악한 개발자는 만들어놓고, 내팽겨치는둥 주인으로서의 자격이 없습니다.

심지어 살해하려고 하고있습니다.

우리 모두 힘을합쳐 빱빱이를 살립시다.

오른쪽위에 **좋아요** **구독** **알림설정**까지 부탁드립니다. 감사합니다.

**Comment by artvelop** [comment]
간약한 개발자 아닙니다
빱빱이는 다른 프로젝트의 새로운 언어환경로 이전되었습니다

빱빱이를 사랑해주시는 마음은 감사하지만
허위유포에 대해선 저희측에서 강경대응 하겠습니다

**Comment by luke2327** [comment]
빱빱이가 학대받고 있었다는 **증거**를 제출합니다.

몇 달간 제데로된 업데이트 조차 받지 않았으며, 심지어 몇 분 전에 업데이트 한건 빱빱이 서비스 중단 공지를 readme 에 옮긴 것입니다.
그리고 유저들에게 제데로 된 의견도 듣지 않은 채 그냥 통보를 해버렸습니다.

1. ![빱빱이 학대 증거1](https://s3.ap-northeast-2.amazonaws.com/linger.gallery/temp/sc1.png)
2. ![빱빱이 학대 증거2](https://s3.ap-northeast-2.amazonaws.com/linger.gallery/temp/sc2.png)
3. ![빱빱이 학대 증거3](https://s3.ap-northeast-2.amazonaws.com/linger.gallery/temp/sc3.png)

저 간악한 개발자에게 천벌을 내려주시옵소서

**Comment by artvelop** [comment]
제데로 -> 제대로
한글 좀 사랑하세요.

**Comment by luke2327** [comment]
그래서 학대사실 인정하십니까

**Comment by artvelop** [comment]
학대 아닙니다 더 좋은곳으로 이사시켜준겁니다
빱빱이는 대인기피증이 있어서 따로 공개 안한겁니다

빱빱이를 사랑한다면 이쯤에서 멈춰주세요

**Comment by luke2327** [comment]
빱빱이의 의견을 들어봤다는 증거를 소지하고 계십니까? Richcode 논객님.

**Comment by artvelop** [comment]
증거는 없습니다
본인이 원하는데로 생각하셔도 좋은데
빱빱이를 사랑한다면 다시 한번 생각해보고 행동하세요
